### ISSUE TITLE
I  met errors  when I do projected band structure

### ISSUE THREAD

**Issue by zrqustc** [SMTG-UCL/sumo#66] opened 2019-07-18 18:18 UTC
When I use sumo-bandplot to plot the projected band structure.
I met this error
"  File "/home/rqzhang/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 696, in _check_bounds
    raise ValueError("A value in x_new is above the interpolation "
ValueError: A value in x_new is above the interpolation range."

If I do not use the Projected, the band structure is OK.

Could you give me some suggestion?

**Comment by ajjackson** [comment] 2019-07-18 18:47
That's interesting. Can you please paste the whole error output? From the above it seems that Sumo is passing an invalid range to Scipy; it would be helpful to know which function in Sumo is doing this.

**Comment by zrqustc** [comment] 2019-07-18 21:38
Thanks for your reply.

This is the script I use:"bandplot(filenames="/scratch/rqzhang/SmB6-Exp/NON/scf/band/vasprun.xml",
        width=12.0,height=8.0,projection_selection=[('Sm', 'f'), ('Sm', 'd')],mode = 'rgb',
        #colours={'Sm': {'f': 'r', 'd': 'b'},'B': {'p': 'g'}},
        ymin=-1, ymax=1)"



And the flowing is the error:


![image](https://user-images.githubusercontent.com/16348056/61493822-2302c880-a97a-11e9-9f67-a21c3048bb66.png)


If I comment on the keywords "projection_selection", everything will get OK.
Thanks！

**Comment by ajjackson** [comment] 2019-07-22 10:32
I'm having trouble reproducing this. Calling `bandplot` from python and setting _projection_selection_ to a list of tuples is working for me in the case of spin-polarised nickel.

I did also manage to run a (poor-quality) open-shell calculation on SnB6 and got an orbital-projected plot with `bandplot(filenames='vasprun.xml', projection_selection=[('B', 'p'), ('Sm', 'd'), ('Sm', 'f')])`.

![band](https://user-images.githubusercontent.com/2511383/61626025-0b765900-ac74-11e9-8182-a8ed62d099b2.png)

SmB6 seems to be quite a difficult system; I'm finding that VASP's wavefunction optimisers tend to blow up unless I use the Sm_3 POTCAR.  But this system is thought to have mixed oxidation states? Something like BANDUP may be a more appropriate tool for the job, to deal with oxidation/magnetic ordering in a larger cell. (Admittedly, it is on our wishlist to have Sumo interact nicely with Bandup.)

Could you take a look at the PROCAR file and check the full set of orbital information is there? I can imagine an error like this occurring if the PROCAR, KPOINTS and vasprun.xml data didn't match up.

**Comment by zrqustc** [comment] 2019-07-22 14:16
Thanks so much for your help and suggestion.
I will try later and if there are some update will let you know.

**Comment by ajjackson** [comment] 2019-07-31 16:04
Have you had any luck with your calculation?

**Comment by zrqustc** [comment] 2019-07-31 16:57
Thanks!
Not yet.  I have checked the PROCAR, KPOINTS and vasprun.xml. The data I
think they are same.
I also try to do other calculations to figure out what happened.

**Comment by ajjackson** [comment] 2019-08-30 12:55
Shall I close this or are you still stuck? If so, can you please generate a minimal example that fails and post the POSCAR, INCAR and KPOINTS files? (Preferably a calculation that is fairly cheap to run!)

**Comment by zrqustc** [comment] 2019-09-27 16:33
Sorry for delaying. Last month I didn’t check this issue. Do you need I send you the PROCAR vasprun.xml and some other files to test?
Thanks!

**Comment by ajjackson** [comment] 2019-10-02 07:43
Can you post your INCAR files?

**Comment by zrqustc** [comment] 2019-10-07 03:45
Sorry for delaying. I am in outside last week. Here is my INCAR.

ADDGRID = True
ALGO = All
EDIFF = 1e-05
EDIFFG = -0.01
ENCUT = 520
IBRION = -1
ICHARG = 0
ISIF = 3
ISMEAR = 0
ISPIN = 2
ISTART = 1
ISYM = 1
KPAR = 2
LASPH = True
#LCHARG = False
LMIXTAU = True
LORBIT = 11
LORBMOM = True
LREAL = False
#LWAVE = False
METAGGA = Scan
NELM = 300
#NELMDL = -5
NELMIN = 20
NPAR = 4
NSW = 0
NEDOS=3000
PREC = A
SIGMA = 0.02
LDAU = True
LDAUJ = 0 0 0
LDAUL = 3 2 -1
LDAUPRINT = 2
LDAUTYPE = 2
LDAUU = 0 0 0
NBANDS = 80

SAXIS =  0 0 1
MAGMOM = 0 0 5.0 0 0 -1.0 6*0.0

LSORBIT   = TRUE
GGA_COMPAT = FALSE

AMIX      = 0.1
BMIX      = 0.00001
AMIX_MAG  = 0.4
BMIX_MAG  = 0.00001

**Comment by zrqustc** [comment] 2019-10-08 17:09
![image](https://user-images.githubusercontent.com/16348056/66416912-807c4380-e9c4-11e9-90da-2837d3fae7ae.png)

**Comment by utf** [comment] 2019-10-08 17:40
Hi @zrqustc, please can you post the full error trace? You can copy and paste the text, you don't need to post a screenshot.

**Comment by zrqustc** [comment] 2019-10-08 20:36
Sure.  Please see the following.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-24997d9ff29e> in <module>
      4       #  elements={'Nd': ('f','d'),'Ni':'d','O':'p'},
      5          ymin=-2, ymax=2,
----> 6         width=12.0,height=8.0)

~/repos/sumo/sumo/cli/bandplot.py in bandplot(filenames, code, prefix, directory, vbm_cbm_marker, projection_selection, mode, interpolate_factor, circle_size, dos_file, cart_coords, ylabel, dos_label, elements, lm_orbitals, atoms, total_only, plot_total, legend_cutoff, gaussian, height, width, ymin, ymax, colours, yscale, style, no_base_style, image_format, dpi, plt, fonts)
    295             plt=plt, dos_plotter=dos_plotter, dos_options=dos_opts,
    296             dos_label=dos_label, fonts=fonts, style=style,
--> 297             no_base_style=no_base_style)
    298     else:
    299         plt = plotter.get_plot(

~/repos/sumo/sumo/plotting/__init__.py in wrapper(fonts, style, no_base_style, *args, **kwargs)
     59 
     60             matplotlib.pyplot.style.use(list_style)
---> 61             return get_plot(*args, **kwargs)
     62 
     63         return wrapper

~/repos/sumo/sumo/plotting/bs_plotter.py in get_projected_plot(self, selection, mode, interpolate_factor, circle_size, projection_cutoff, zero_to_efermi, ymin, ymax, width, height, vbm_cbm_marker, ylabel, dpi, plt, dos_plotter, dos_options, dos_label, dos_aspect, aspect, fonts, style, no_base_style)
    379             dx = (distances[1] - distances[0]) / interpolate_factor
    380             temp_dists = np.arange(distances[0], distances[-1], dx)
--> 381             bands = interp1d(distances, bands, axis=1)(temp_dists)
    382             weights = interp1d(distances, weights, axis=2)(temp_dists)
    383             distances = temp_dists

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py in __call__(self, x)
     77         """
     78         x, x_shape = self._prepare_x(x)
---> 79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)
     81 

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in _evaluate(self, x_new)
    662         y_new = self._call(self, x_new)
    663         if not self._extrapolate:
--> 664             below_bounds, above_bounds = self._check_bounds(x_new)
    665             if len(y_new) > 0:
    666                 # Note fill_value must be broadcast up to the proper size

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in _check_bounds(self, x_new)
    694                              "range.")
    695         if self.bounds_error and above_bounds.any():
--> 696             raise ValueError("A value in x_new is above the interpolation "
    697                              "range.")
    698 

ValueError: A value in x_new is above the interpolation range.

**Comment by utf** [comment] 2019-10-08 20:50
Hmmm, this is pretty strange. I guess this must be some floating point precision errors cropping up. I think I have a fix, but could you try one thing for me. Can you change line 380 in `~/repos/sumo/sumo/plotting/bs_plotter.py` from:

```python
temp_dists = np.arange(distances[0], distances[-1], dx)
```

to 

```python
temp_dists = np.arange(distances[0], distances[-1], dx)
print("d0", distances[0], "d-1", distances[-1])
print("min_d", min(distances), "max_d", max(distances))
print("min_temp", min(temp_dists), "max_temp", max(temp_dists))
```

And then rerun and paste the output that gets printed to the terminal.

Thanks

**Comment by zrqustc** [comment] 2019-10-09 02:41
Thanks for your reply.
I have changed the code following your suggestion, the following is the output.

~/repos/sumo/sumo/cli/bandplot.py in bandplot(filenames, code, prefix, directory, vbm_cbm_marker, projection_selection, mode, interpolate_factor, circle_size, dos_file, cart_coords, ylabel, dos_label, elements, lm_orbitals, atoms, total_only, plot_total, legend_cutoff, gaussian, height, width, ymin, ymax, colours, yscale, style, no_base_style, image_format, dpi, plt, fonts)
    295             plt=plt, dos_plotter=dos_plotter, dos_options=dos_opts,
    296             dos_label=dos_label, fonts=fonts, style=style,
--> 297             no_base_style=no_base_style)
    298     else:
    299         plt = plotter.get_plot(

~/repos/sumo/sumo/plotting/__init__.py in wrapper(fonts, style, no_base_style, *args, **kwargs)
     59 
     60             matplotlib.pyplot.style.use(list_style)
---> 61             return get_plot(*args, **kwargs)
     62 
     63         return wrapper

~/repos/sumo/sumo/plotting/bs_plotter.py in get_projected_plot(self, selection, mode, interpolate_factor, circle_size, projection_cutoff, zero_to_efermi, ymin, ymax, width, height, vbm_cbm_marker, ylabel, dpi, plt, dos_plotter, dos_options, dos_label, dos_aspect, aspect, fonts, style, no_base_style)
    379             dx = (distances[1] - distances[0]) / interpolate_factor
    380             temp_dists = np.arange(distances[0], distances[-1], dx)
--> 381             print("d0", distances[0], "d-1", distances[-1])
    382             print("min_d", min(distances), "max_d", max(distances))
    383             print("min_temp", min(temp_dists), "max_temp", max(temp_dists))

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py in __call__(self, x)
     77         """
     78         x, x_shape = self._prepare_x(x)
---> 79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)
     81 

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in _evaluate(self, x_new)
    662         y_new = self._call(self, x_new)
    663         if not self._extrapolate:
--> 664             below_bounds, above_bounds = self._check_bounds(x_new)
    665             if len(y_new) > 0:
    666                 # Note fill_value must be broadcast up to the proper size

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in _check_bounds(self, x_new)
    694                              "range.")
    695         if self.bounds_error and above_bounds.any():
--> 696             raise ValueError("A value in x_new is above the interpolation "
    697                              "range.")
    698 

ValueError: A value in x_new is above the interpolation range.

**Comment by utf** [comment] 2019-10-10 00:29
You need to restart the kernel of the notebook you are using as the updated code has not been loaded properly.

Please restart the notebook and try running the code again. Additional information should be printed out before the error message.

**Comment by zrqustc** [comment] 2019-10-10 01:24
Thanks. I restarted notebook and got the information. Please see the following.

d0 0.0 d-1 0.8090767866786629
min_d 0.0 max_d 0.8090767866786629
min_temp 0.0 max_temp 0.8040200567619213
d0 0.8090767866786629 d-1 1.618153573357326
min_d 0.8090767866786629 max_d 1.618153573357326
min_temp 0.8090767866786629 max_temp 1.6181535733573291
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-24997d9ff29e> in <module>
      4       #  elements={'Nd': ('f','d'),'Ni':'d','O':'p'},
      5          ymin=-2, ymax=2,
----> 6         width=12.0,height=8.0)

~/repos/sumo/sumo/cli/bandplot.py in bandplot(filenames, code, prefix, directory, vbm_cbm_marker, projection_selection, mode, interpolate_factor, circle_size, dos_file, cart_coords, ylabel, dos_label, elements, lm_orbitals, atoms, total_only, plot_total, legend_cutoff, gaussian, height, width, ymin, ymax, colours, yscale, style, no_base_style, image_format, dpi, plt, fonts)
    295             plt=plt, dos_plotter=dos_plotter, dos_options=dos_opts,
    296             dos_label=dos_label, fonts=fonts, style=style,
--> 297             no_base_style=no_base_style)
    298     else:
    299         plt = plotter.get_plot(

~/repos/sumo/sumo/plotting/__init__.py in wrapper(fonts, style, no_base_style, *args, **kwargs)
     59 
     60             matplotlib.pyplot.style.use(list_style)
---> 61             return get_plot(*args, **kwargs)
     62 
     63         return wrapper

~/repos/sumo/sumo/plotting/bs_plotter.py in get_projected_plot(self, selection, mode, interpolate_factor, circle_size, projection_cutoff, zero_to_efermi, ymin, ymax, width, height, vbm_cbm_marker, ylabel, dpi, plt, dos_plotter, dos_options, dos_label, dos_aspect, aspect, fonts, style, no_base_style)
    382             print("min_d", min(distances), "max_d", max(distances))
    383             print("min_temp", min(temp_dists), "max_temp", max(temp_dists))
--> 384             bands = interp1d(distances, bands, axis=1)(temp_dists)
    385             weights = interp1d(distances, weights, axis=2)(temp_dists)
    386             distances = temp_dists

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/polyint.py in __call__(self, x)
     77         """
     78         x, x_shape = self._prepare_x(x)
---> 79         y = self._evaluate(x)
     80         return self._finish_y(y, x_shape)
     81 

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in _evaluate(self, x_new)
    662         y_new = self._call(self, x_new)
    663         if not self._extrapolate:
--> 664             below_bounds, above_bounds = self._check_bounds(x_new)
    665             if len(y_new) > 0:
    666                 # Note fill_value must be broadcast up to the proper size

~/repos/miniconda3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py in _check_bounds(self, x_new)
    694                              "range.")
    695         if self.bounds_error and above_bounds.any():
--> 696             raise ValueError("A value in x_new is above the interpolation "
    697                              "range.")
    698 

ValueError: A value in x_new is above the interpolation range.

**Comment by zrqustc** [comment] 2019-10-18 22:00
Hi @utf Is there some method for debugging this?

Thanks!

**Comment by utf** [comment] 2019-10-21 00:27
@zrqustc I've just pushed a new version of sumo to github/pypi. Can you try updating and let me know if that fixes your problem.

**Comment by zrqustc** [comment] 2019-10-21 02:38
@utf Thanks so much! I have tested it. It works.

**Closed** 2019-10-21 02:46 UTC

**Comment by muhammadaliaskari** [comment] 2020-12-29 13:11
is it possible to plot a projected band structure of a composite with more than 3 elements? --mode stacked does not work in my case...
