### ISSUE TITLE
KeyError: 'up', when setting spin='up'

### ISSUE THREAD

**Issue by zrqustc** [SMTG-UCL/sumo#94] opened 2020-03-07 04:43 UTC
Dear developers,

When I want to plot one spin channel, I got KeyError: 'up'.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-039865f8599b> in <module>
     10          spin='up',
     11          ymin=-1, ymax=1,
---> 12         width=a,height=b)
     13 #for i in range(72):
     14 #    plt.plot(X[i,:], Y[i,:],linewidth=2.0,c='b')

~/.local/lib/python3.6/site-packages/sumo/cli/bandplot.py in bandplot(filenames, code, prefix, directory, vbm_cbm_marker, projection_selection, mode, interpolate_factor, circle_size, dos_file, cart_coords, scissor, ylabel, dos_label, elements, lm_orbitals, atoms, spin, total_only, plot_total, legend_cutoff, gaussian, height, width, ymin, ymax, colours, yscale, style, no_base_style, image_format, dpi, plt, fonts)
    311             plt=plt, dos_plotter=dos_plotter, dos_options=dos_opts,
    312             dos_label=dos_label, fonts=fonts, style=style,
--> 313             no_base_style=no_base_style, spin=spin)
    314 
    315     if save_files:

~/.local/lib/python3.6/site-packages/sumo/plotting/__init__.py in wrapper(fonts, style, no_base_style, *args, **kwargs)
     59 
     60             matplotlib.pyplot.style.use(list_style)
---> 61             return get_plot(*args, **kwargs)
     62 
     63         return wrapper

~/.local/lib/python3.6/site-packages/sumo/plotting/bs_plotter.py in get_plot(self, zero_to_efermi, ymin, ymax, width, height, vbm_cbm_marker, ylabel, dpi, plt, plot_dos_legend, dos_plotter, dos_options, dos_label, dos_aspect, aspect, fonts, style, no_base_style, spin)
    164 
    165         elif spin is not None:
--> 166             is_vb = self._bs.bands[spin] <= self._bs.get_vbm()['energy']
    167         elif self._bs.is_spin_polarized or self._bs.is_metal():
    168             is_vb = [True]

KeyError: 'up'

**Comment by utf** [comment] 2020-03-08 17:51
@kavanase can you look into this?

**Comment by kavanase** [comment] 2020-03-10 13:02
Dear @zrqustc,
Thank you for raising this issue and attaching your error log. 
It seems that the `spin` argument being passed to `bs_plotter.py` is not being correctly parsed and converted to a pymatgen `Spin.up` object. From your error log, it appears you are using the `sumo` Python API functions rather than the command line, and this is what leads to the error. 
From inspection of the code and your error log, I can see that the `string_to_spin` conversion function (which converts the input `--spin` flag to a pymatgen `Spin` object) is only applied to the cli  argument parser, and so does not convert your `spin` argument when directly using the `bandplot` function. This is a minor bug which I will fix now.
Thanks again for raising this issue!

**Comment by zrqustc** [comment] 2020-03-10 14:28
Okay, Thanks for your reply.

Best,
Ruiqi

**Comment by utf** [comment] 2020-03-10 17:00
This issue should now be fixed in master. Can you try pulling the latest changes in from GitHub and testing again?

**Comment by zrqustc** [comment] 2020-03-10 18:07
Sure, I am going to test now and give you feedback.

Best,
Ruiqi

**Comment by zrqustc** [comment] 2020-03-10 18:59
Got a new TypeError.  

See the following:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-305ffb012099> in <module>
     10          spin='up',
     11          ymin=-1, ymax=1,
---> 12         width=a,height=b)
     13 #for i in range(72):
     14 #    plt.plot(X[i,:], Y[i,:],linewidth=2.0,c='b')

~/repos/miniconda3/lib/python3.6/site-packages/sumo-1.4.0-py3.6.egg/sumo/cli/bandplot.py in bandplot(filenames, code, prefix, directory, vbm_cbm_marker, projection_selection, mode, interpolate_factor, circle_size, dos_file, cart_coords, scissor, ylabel, dos_label, elements, lm_orbitals, atoms, spin, total_only, plot_total, legend_cutoff, gaussian, height, width, ymin, ymax, colours, yscale, style, no_base_style, image_format, dpi, plt, fonts)
    312             plt=plt, dos_plotter=dos_plotter, dos_options=dos_opts,
    313             dos_label=dos_label, fonts=fonts, style=style,
--> 314             no_base_style=no_base_style, spin=spin)
    315 
    316     if save_files:

~/repos/miniconda3/lib/python3.6/site-packages/sumo-1.4.0-py3.6.egg/sumo/plotting/__init__.py in wrapper(fonts, style, no_base_style, *args, **kwargs)
     59 
     60             matplotlib.pyplot.style.use(list_style)
---> 61             return get_plot(*args, **kwargs)
     62 
     63         return wrapper

~/repos/miniconda3/lib/python3.6/site-packages/sumo-1.4.0-py3.6.egg/sumo/plotting/bs_plotter.py in get_plot(self, zero_to_efermi, ymin, ymax, width, height, vbm_cbm_marker, ylabel, dpi, plt, plot_dos_legend, dos_plotter, dos_options, dos_label, dos_aspect, aspect, fonts, style, no_base_style, spin)
    164 
    165         elif spin is not None:
--> 166             is_vb = self._bs.bands[spin] <= self._bs.get_vbm()['energy']
    167         elif self._bs.is_spin_polarized or self._bs.is_metal():
    168             is_vb = [True]

TypeError: '<=' not supported between instances of 'float' and 'NoneType'

**Comment by kavanase** [comment] 2020-03-10 19:18
Dear @zrqustc,
Thank you for the quick feedback. From the TypeError, it is suggesting that the issue is now coming from `self._bs.get_vbm()['energy']` being `NoneType`, rather than from `self._bs.bands[spin]`, which is a `float` type as expected. Is your system semiconducting (does it have a well-defined VBM)?

**Comment by zrqustc** [comment] 2020-03-10 19:22
Thanks.  My system is metal, not a semiconductor.

**Comment by kavanase** [comment] 2020-03-10 19:26
Thanks for the quick reply. The issue is as I expected, the spin-selection functionality of `sumo` has been set up to work with semiconducting systems and is currently incompatible with metallic systems. I will update now to include spin-selection capability for metallic systems. Thanks for your patience!

**Comment by utf** [comment] 2020-03-10 19:26
I will submit a fix now.

**Comment by zrqustc** [comment] 2020-03-10 19:27
Great! Thanks for the update.

**Comment by utf** [comment] 2020-03-10 19:54
Ok, I pushed fixes in 027496ccbb811c2da57c162ae2dbed8c76a8ee5e and 0488ce8d4c537aaf10330d0ae8d14619142c299a

Can you please try again and let me know.

**Comment by zrqustc** [comment] 2020-03-10 20:02
Sure. I am testing now and give you feedback later.

**Comment by zrqustc** [comment] 2020-03-10 20:37
Thanks, Alex.

I have tested the code. If I don't use the projection mode, everything is
fine.
But, when I use the projection mode, it will give this error;



---------------------------------------------------------------------------KeyError
                                 Traceback (most recent call
last)<ipython-input-8-181f813e3250> in <module>     10
spin='down',     11          ymin=-1, ymax=1,---> 12
width=a,height=b)     13 #for i in range(72):     14 #
plt.plot(X[i,:], Y[i,:],linewidth=2.0,c='b')
~/repos/miniconda3/lib/python3.6/site-packages/sumo-1.4.0-py3.6.egg/sumo/cli/bandplot.py
in bandplot(filenames, code, prefix, directory, vbm_cbm_marker,
projection_selection, mode, interpolate_factor, circle_size, dos_file,
cart_coords, scissor, ylabel, dos_label, elements, lm_orbitals, atoms,
spin, total_only, plot_total, legend_cutoff, gaussian, height, width,
ymin, ymax, colours, yscale, style, no_base_style, image_format, dpi,
plt, fonts)    305             plt=plt, dos_plotter=dos_plotter,
dos_options=dos_opts,    306             dos_label=dos_label,
fonts=fonts, style=style,--> 307
no_base_style=no_base_style, spin=spin)    308     else:    309
 plt = plotter.get_plot(
~/repos/miniconda3/lib/python3.6/site-packages/sumo-1.4.0-py3.6.egg/sumo/plotting/__init__.py
in wrapper(fonts, style, no_base_style, *args, **kwargs)     59
60             matplotlib.pyplot.style.use(list_style)---> 61
   return get_plot(*args, **kwargs)     62      63         return
wrapper
~/repos/miniconda3/lib/python3.6/site-packages/sumo-1.4.0-py3.6.egg/sumo/plotting/bs_plotter.py
in get_projected_plot(self, selection, mode, interpolate_factor,
circle_size, projection_cutoff, zero_to_efermi, ymin, ymax, width,
height, vbm_cbm_marker, ylabel, dpi, plt, dos_plotter, dos_options,
dos_label, plot_dos_legend, dos_aspect, aspect, fonts, style,
no_base_style, spin)    389     390         proj =
get_projections_by_branches(self._bs, selection,--> 391
                            normalise='select')    392     393
# nd is branch index
~/repos/miniconda3/lib/python3.6/site-packages/sumo-1.4.0-py3.6.egg/sumo/electronic_structure/bandstructure.py
in get_projections_by_branches(bs, selection, normalise)     70
"""     71     spins = bs.bands.keys()---> 72     projections =
get_projections(bs, selection, normalise=normalise)     73      74
branches = []
~/repos/miniconda3/lib/python3.6/site-packages/sumo-1.4.0-py3.6.egg/sumo/electronic_structure/bandstructure.py
in get_projections(bs, selection, normalise)    179         proj =
dict(zip(spins, [np.zeros((nbands, nkpts))] * len(spins)))    180
   for spin, orbital in it.product(spins, orbitals):--> 181
 proj[spin] += dict_proj[element][orbital][spin]    182     183
     if normalise == 'select':
KeyError: <Spin.up: 1>

**Comment by utf** [comment] 2020-03-10 21:24
Can you copy and paste the code you are running when you get this error?

Can you also check that your VASP calculation definitely has band structure projections?

**Comment by zrqustc** [comment] 2020-03-10 21:31
Let me test one more example. Maybe it is my mistake.

**Comment by zrqustc** [comment] 2020-03-10 21:36
Thanks Alex.
All the issues are fixed now.
It is my mistake, the first example I test doesn't run normally.
Thanks again for your help.

Best regards,
Ruiqi

**Comment by utf** [comment] 2020-03-10 21:39
Great! Thanks for the bug report.

**Closed by utf** 2020-03-10 21:39 UTC
