### ISSUE TITLE
sumo-bandplot rgb mode fails

### ISSUE THREAD

**Issue by bugaboo** [SMTG-UCL/sumo#170] opened 2022-07-14 20:38 UTC
I run command
`sumo-bandplot --project B,N --mode rgb`
and get the following.
`Traceback (most recent call last):
  File "/home/bugaboo/.local/bin/sumo-bandplot", line 8, in <module>
    sys.exit(main())
  File "/home/bugaboo/.local/lib/python3.10/site-packages/sumo/cli/bandplot.py", line 880, in main
    bandplot(
  File "/home/bugaboo/.local/lib/python3.10/site-packages/sumo/cli/bandplot.py", line 415, in bandplot
    plt = plotter.get_projected_plot(
  File "/home/bugaboo/.local/lib/python3.10/site-packages/sumo/plotting/__init__.py", line 58, in wrapper
    return get_plot(*args, **kwargs)
  File "/home/bugaboo/.local/lib/python3.10/site-packages/sumo/plotting/bs_plotter.py", line 612, in get_projected_plot
    lc = colorline(
  File "/home/bugaboo/.local/lib/python3.10/site-packages/sumo/plotting/__init__.py", line 215, in colorline
    c = get_interpolated_colors(color1, color2, color3, w, colorspace=colorspace)
  File "/home/bugaboo/.local/lib/python3.10/site-packages/sumo/plotting/__init__.py", line 285, in get_interpolated_colors
    basis1 * weights[:, 0][:, None]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
`
The 'stacked' mode executes fine. Same happens with 3 selections for orbitals. The previous version 2.2.5 of sumo-bandplot worked fine with the rgb mode for the same VASP calculation.
Upon fiddling with the code I found that it always happens for branch index nd=1 for me. The definition is at the line 558 of bs_plotter.py.

**Comment by utf** [comment] 2022-07-15 09:19
Interesting. I can't reproduce on the band structures in `sumo/tests/data/OsO2` or `tests/data/Cs2SnI6/bandstructure`. Are you able to upload a vasprun.xml?

**Comment by bugaboo** [comment] 2022-07-18 08:49
> 

[vasprun.tar.gz](https://github.com/SMTG-UCL/sumo/files/9130609/vasprun.tar.gz)
Here it is. It might be because my vasp version is 5.4.1.

**Comment by utf** [comment] 2022-07-18 09:23
Thank you. This should now be fixed in the latest version of sumo (v2.3.3)

**Closed by utf** 2022-07-18 09:23 UTC

**Comment by bugaboo** [comment] 2022-07-18 09:45
Yes, that fixed it for me. Thank you!
