### ISSUE TITLE
How can I add a dotted or dashed line at Fermi level

### ISSUE THREAD

**Issue by kcbhamu** [SMTG-UCL/sumo#147] opened 2021-08-24 08:00 UTC
Hii Again,
Sorry for the multiple questions.

How can I add a horizontal dotted or dashed line at the Fermi level (top of the valence band at y-axis=0)?
Thanks

**Comment by ajjackson** [comment] 2021-08-24 11:04
This is a duplicate of #135

**Closed by ajjackson** 2021-08-24 11:04 UTC
